import Head from 'next/head';
import Image from 'next/image'
import Style from '../../frontend/style.css';
import { Row, Col } from "reactstrap";
import 'bootstrap/dist/css/bootstrap.min.css';
export default function Pokemon() {
return (
<div>
  <Head>
    <title>Pokemon home page</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    
    <link rel="stylesheet" href={Style}/>
  </Head>
  <header>
    
  </header>
  <main>
    
    <section className="section1">
      <div className="container">
        <div className="p-4 logo d-flex justify-content-center align-items-center">
          <Image width="0" height="0"  src="/asset/Logo.png" className="Image-fluid" alt="" sizes="100vw" style={{ width: 'auto', height: 'auto' }}/>
        </div>
        <div className="pokemon-container">
          <div className="pokemons">
            <div class="card border-0" style={{width: "14rem"}}>
             <div className="card-container">
                <Image width="0" height="0" sizes="100vw" src="/asset/Image01.png" className="card-Image-top p-2" alt="..." style={{ width: 'auto', height: 'auto' }} />
              <div className="card-body">
                <h6 className="card-title">Bulbasaur</h6>
                <a href="#" className="btn btn-primary btn-sm mx-1">Grass</a>
                <a href="#" className="btn btn-primary btn-sm mx-1">Poison</a>
              </div>
             </div>
            
            </div>
          </div>
        </div>
        
      </div>
      
      
      
    </section>
    <section className="section2">
      <div className="description-container  mx-3">
        <div className="description  position-absolute px-5 mx-5" style={{zIndex: '1'}}>
          <div className="description-title d-flex justify-content-center align-items-center ">
            <Image width="0" height="0" sizes="100vw" src="/asset/Brush.png" className="Image-fluid" alt="" style={{ width: 'auto', height: 'auto' }} />
            <h1 className="p-4 text-center text-primary fw-bold">Ash & Pikachu Arrive in <br/> Pokemon Universe</h1>
          </div>
          <div className="description-box position-relative d-flex ustify-content-center align-items-center">
            <div className="container">
              
              <Row>
              <Col md="8" className="pe-0">
              <Row>
              <Col md="8" className="">
              <Row>
              <Col md="12" >
              Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              specimen book. It has survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged.
              </Col>
              </Row>
              </Col>
              <Col md="4" className="px-4 d-flex justify-content-center align-items-center" style={{marginTop:'90px'}}>
              <Image width="0" height="0" sizes="100vw" src="/asset/Image03.png" className="Image-fluid" alt="" style={{ width: 'auto', height: 'auto' }} />
              </Col>
              </Row>
              <Row>
              <Col md="8">
              <Row>
              <Col md="8" className="py-2">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              specimen book. It has survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged.
              </Col>
              <Col md="4" className="py-3 pe-0 ps-4">
              <Image width="0" height="0" sizes="100vw" src="/asset/Image04.png" className="Image-fluid" alt="" />
              </Col>
              </Row>
              </Col>
              
              <Col md="4" className="px-4  d-flex justify-content-center align-items-center" style={{marginTop:'185px'}}>
              <Image width="0" height="0" sizes="100vw" src="/asset/Image02.png" className="Image-fluid" alt="" style={{ width: 'auto', height: 'auto' }}/>
              </Col>
              </Row>
              <Row>
              <Col md="12" className="py-5 mt-5">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              specimen book. It has survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged.Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              specimen book. It has survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged.
              </Col>
              
              </Row>
              </Col>
              <Col md="4" className="ps-0 ">
              
              <Row>
              <Col md="12" className="ps-0">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type
              </Col>
              </Row>
              <Row>
              <Col md="6" className="ps-0 pe-0">
              <Image width="0" height="0" sizes="100vw" src="/asset/Image05.png" className="Image-fluid" alt=""  style={{ width: 'auto', height: 'auto' }}/>
              </Col>
              <Col md="6" className="ps-0 pe-0">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              
              </Col>
              </Row>
              <Row>
              <Col md="6" className="ps-0 pe-0">
              <Image width="0" height="0" sizes="100vw" src="/asset/Image01.png" className="Image-fluid" alt=""  style={{ width: 'auto', height: 'auto' }}/>
              </Col>
              <Col md="6" className="ps-0 pe-0">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              
              </Col>
              </Row>
              <Row>
              <Col md="12">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and
              </Col>
              </Row>
              </Col>
              </Row>
              
            </div>
          </div>
          
        </div>
      </div>
      <div className="d-flex justify-content-between position-relative" style={{zIndex:"-1"}}>
        <Image
        className="p-0 Image-fluid"
        src="/asset/Left.png"
        alt="bg"
        width="100"
        height="500"
        />
        <Image
        className="Image-fluid"
        src="/asset/Left.png"
        alt="bg"
        width="100"
        height="500"
        />
      </div>
    </section>
    
    
  </main>

</div>
);
}